/* Autogenerated by png2wx.pl on Thu Nov  4 13:06:52 2010 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

#include <wx/filename.h>
#include <wx/mstream.h>

extern void initialize_images( void );

extern wxBitmap *_img_logbook_pi;
extern wxBitmap *_img_logbook;
extern const wxBitmap *_img_Bullet_green;
extern const wxBitmap *_img_Bullet_red;
extern const wxBitmap *_img_Bullet_yellow;

#ifdef PLUGIN_USE_SVG
extern wxString _svg_logbookkonni;
extern wxString _svg_logbookkonni_rollover;
extern wxString _svg_logbookkonni_toggled;
#endif


#endif /* ICONS_H */
